export {default as Home} from './Home'
export {default as ProductEdit} from './ProductEdit'
export {default as Productlist} from './Productlist'
export {default as Reset} from './Reset'
export {default as SignUp} from './SignUp'
export {default as SignIn} from './SignIn'